### ISSUE TITLE
При запуске python main.py ошибка

### ISSUE THREAD

**Issue by miki-sol** [B0R9F3D9/Zetachain-earn-xp#1]
C:\Users\micha\OneDrive\Рабочий стол\Zetachain-earn-xp-main>python main.py
Traceback (most recent call last):
  File "C:\Users\micha\OneDrive\Рабочий стол\Zetachain-earn-xp-main\main.py", line 10, in <module>
    from modules import *
  File "C:\Users\micha\OneDrive\Рабочий стол\Zetachain-earn-xp-main\modules\__init__.py", line 1, in <module>
    from .account import Account
  File "C:\Users\micha\OneDrive\Рабочий стол\Zetachain-earn-xp-main\modules\account.py", line 16, in <module>
    class Account:
  File "C:\Users\micha\OneDrive\Рабочий стол\Zetachain-earn-xp-main\modules\account.py", line 17, in Account
    def __init__(self, account_id: int, key_mnemonic: str, proxy: str | None = None, withdraw_address: str | None = None) -> None:
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

Делал все по инструкции, юзаю python 3,9

**Comment by B0R9F3D9** [comment]
Обнови питон, минимум 3.10
